# The lore that will be added to signed items
#
# %PLAYER%  | Player displayname
# %DATE%    | Date and time
#
# PlaceholderAPI is supported!
lore:
  - "Signed by %PLAYER%"
  - "%DATE%"
  - ""

# Added above the note, only if a note exists
#
# %PLAYER%  | Player displayname
# %DATE%    | Date and time
#
# PlaceholderAPI is supported!
note-prefix:
  - "- Note -"

# Added below the note, only if a note exists
#
# %PLAYER%  | Player displayname
# %DATE%    | Date and time
#
# PlaceholderAPI is supported!
note-suffix:
  - "- End of Note -"

# Format of the date variable
#
# European: dd.MM.yyyy hh:mm:ss
date-format: "MM/dd/yyyy hh:mm:ss"

# List of items that can be used even when they're signed
use-whitelist: 
  - BOW
  - SHIELD
  - CROSSBOW

# Limits for the note
note-chars-per-line: 32
note-max-lines: 3

# Change what arrives in chat!
messages:
  sign-success: "&aThe item has been signed!"
  note-too-long: "&cThe message is too long!"
  use-disabled: "&cSigned items cannot be used!"
  no-item: "&cYou are not holding an item!"
  no-permission: "&cYou are not permitted to do this!"
  no-overwrite: "&cYou are not allowed to overwrite signed items!"