main: games.yinga.Sign
name: Sign
author: Xenorio
version: 1.0.2
api-version: 1.18

softdepend: [PlaceholderAPI]

commands:
  sign:
    description: 'Signs an item'
    usage: 'sign [note]'
    permission: 'sign.create'